apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  proxy:
    networking:
      trafficControl:
        outbound:
          policy: REGISTRY_ONLY  #ALLOW_ANY (default)
    accessLogging:
      file:
        name: /dev/stdout
  tracing:
    sampling: 10000
    type: Jaeger
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.0
  telemetry:
    type: Istiod
  security:
    dataPlane:
      mtls: false
      automtls: false
    controlPlane:
      mtls: false
