apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-int-es
spec:
  strategy: production
  query:
    replicas: 3
  collector:
    replicas: 3
  storage:
    type: elasticsearch
    elasticsearch:
      nodeCount: 3
      redundancyPolicy: SingleRedundancy 
      storage: 
        storageClassName: gp2
        size: 5Gi
      resources: 
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          memory: 4Gi
    esIndexCleaner:
      enabled: true
      numberOfDays: 7
      schedule: "55 23 *  *  *"
